routes/web.php
        Route::post('validarDataCalendario', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'validarDataCalendario', 'uses' => 'PeriodoAvaliacaosController@validarDataCalendario']);
        Route::post('updatePeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'updatePeriodo', 'uses' => 'PeriodoAvaliacaosController@update']);
        Route::post('removerPeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'removerPeriodo', 'uses' => 'PeriodoAvaliacaosController@destroy']);

        # rotas para eventos
        Route::get('gridEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'gridEvento', 'uses' => 'EventosController@grid']);
        Route::post('getTipoEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getTipoEvento', 'uses' => 'EventosController@getTipoEvento']);
        Route::post('getDiaLetivo/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getDiaLetivo', 'uses' => 'EventosController@getDiaLetivo']);
        Route::post('storeEvento', ['middleware' => 'permission:calendario.add.evento', 'as' => 'storeEvento', 'uses' => 'EventosController@store']);
        Route::post('updateEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'updateEvento', 'uses' => 'EventosController@update']);
        Route::post('removerEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'removerEvento', 'uses' => 'EventosController@destroy']);
        Route::post('getDiaSemana', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getDiaSemana', 'uses' => 'EventosController@getDiaSemana']);
    });

    #Rotas das formas de avaliações
    Route::group(['prefix' => 'formaAvaliacao', 'as' => 'formaAvaliacao.'], function () {
        Route::get('index', ['middleware' => 'permission:forma.avaliacao.select', 'as' => 'index', 'uses' => 'FormaAvaliacoesController@index']);
        Route::get('grid', ['middleware' => 'permission:forma.avaliacao.select', 'as' => 'grid', 'uses' => 'FormaAvaliacoesController@grid']);
        Route::get('create', ['middleware' => 'permission:forma.avaliacao.store', 'as' => 'create', 'uses' => 'FormaAvaliacoesController@create']);
        Route::post('store', ['middleware' => 'permission:forma.avaliacao.store', 'as' => 'store', 'uses' => 'FormaAvaliacoesController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:forma.avaliacao.update', 'as' => 'edit', 'uses' => 'FormaAvaliacoesController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:forma.avaliacao.update', 'as' => 'update', 'uses' => 'FormaAvaliacoesController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:forma.avaliacao.destroy', 'as' => 'destroy', 'uses' => 'FormaAvaliacoesController@destroy']);

        # Rotas para niveis de alfabetizacao
        Route::get('nivelAlfabetizacao/grid/{id}', ['as' => 'nivelAlfabetizacao.grid', 'uses' => 'FormaAvaliacoesController@gridNiveis']);
        Route::post('nivelAlfabetizacao/store', ['as' => 'nivelAlfabetizacao.store', 'uses' => 'FormaAvaliacoesController@storeNivel']);
        Route::post('nivelAlfabetizacao/destroy/{id}', ['as' => 'nivelAlfabetizacao.destroy', 'uses' => 'FormaAvaliacoesController@destroyNivel']);
    });

    # Rotas do aluno
    Route::group(['prefix' => 'aluno', 'as' => 'aluno.'], function () {
        Route::get('index', ['middleware' => 'permission:aluno.select', 'as' => 'index', 'uses' => 'AlunoController@index']);
        Route::get('grid', ['middleware' => 'permission:aluno.select', 'as' => 'grid', 'uses' => 'AlunoController@grid']);
        Route::get('create', ['middleware' => 'permission:aluno.store', 'as' => 'create', 'uses' => 'AlunoController@create']);
        Route::post('store', ['middleware' => 'permission:aluno.store', 'as' => 'store', 'uses' => 'AlunoController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:aluno.update', 'as' => 'edit', 'uses' => 'AlunoController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:aluno.update', 'as' => 'update', 'uses' => 'AlunoController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:aluno.destroy', 'as' => 'destroy', 'uses' => 'AlunoController@destroy']);

        Route::get('getImgAluno/{id}', ['as' => 'getImgAluno', 'uses' => 'AlunoController@getImgAluno']);

        Route::post('findBairro', ['as' => 'findBairro', 'uses' => 'AlunoController@findBairro']);
        Route::post('findCidade', ['as' => 'findCidade', 'uses' => 'AlunoController@findCidade']);
        Route::post('searchCpf', ['as' => 'searchCpf', 'uses' => 'AlunoController@searchCpf']);

        # rotas para alunos turmas
        Route::get('gridAlunoTurma/{id}', ['middleware' => 'permission:aluno.matricula', 'as' => 'gridAlunoTurma', 'uses' => 'AlunoTurmasController@grid']);
        Route::post('getTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'getTurma', 'uses' => 'AlunoTurmasController@getTurma']);
        Route::post('getTurmaMudanca', ['as' => 'getTurmaMudanca', 'uses' => 'AlunoTurmasController@getTurmaMudanca']);
        Route::post('storeAlunoTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'storeAlunoTurma', 'uses' => 'AlunoTurmasController@store']);
        Route::post('getDadosTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'getDadosTurma', 'uses' => 'AlunoTurmasController@getDadosTurma']);
        Route::post('storeMudarTurma', ['as' => 'storeMudarTurma', 'uses' => 'AlunoTurmasController@storeMudarTurma']);
        //Route::post('updateTelefone/{id}', ['as' => 'updateTelefone', 'uses' => 'TelefonesController@update']);
       //Route::post('removerTelefone/{id}', ['as' => 'removerTelefone', 'uses' => 'TelefonesController@destroy']);
    });

    # Rotas dos tipos de eventos
    Route::group(['prefix' => 'tipoEvento', 'as' => 'tipoEvento.'], function () {
        Route::get('index', ['middleware' => 'permission:tipo.evento.select', 'as' => 'index', 'uses' => 'TipoEventosController@index']);
        Route::get('grid', ['middleware' => 'permission:tipo.evento.select', 'as' => 'grid', 'uses' => 'TipoEventosController@grid']);
        Route::get('create', ['middleware' => 'permission:tipo.evento.store', 'as' => 'create', 'uses' => 'TipoEventosController@create']);
        Route::post('store', ['middleware' => 'permission:tipo.evento.store', 'as' => 'store', 'uses' => 'TipoEventosController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:tipo.evento.update', 'as' => 'edit', 'uses' => 'TipoEventosController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:tipo.evento.update', 'as' => 'update', 'uses' => 'TipoEventosController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:tipo.evento.destroy', 'as' => 'destroy', 'uses' => 'TipoEventosController@destroy']);
    });

    # Rotas dos perídos de avaliação
    Route::group(['prefix' => 'periodo', 'as' => 'periodo.'], function () {
        Route::get('index', ['middleware' => 'permission:periodo.select', 'as' => 'index', 'uses' => 'PeriodoController@index']);
        Route::get('grid', ['middleware' => 'permission:periodo.select', 'as' => 'grid', 'uses' => 'PeriodoController@grid']);
        //Route::get('grid', ['middleware' => 'permission:periodo.select', 'as' => 'grid', 'uses' => 'PeriodoController@grid']);
        Route::get('create', ['middleware' => 'permission:periodo.store', 'as' => 'create', 'uses' => 'PeriodoController@create']);
        Route::post('store', ['middleware' => 'permission:periodo.store', 'as' => 'store', 'uses' => 'PeriodoController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:periodo.update', 'as' => 'edit', 'uses' => 'PeriodoController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:periodo.update', 'as' => 'update', 'uses' => 'PeriodoController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:periodo.destroy', 'as' => 'destroy', 'uses' => 'PeriodoController@destroy']);
    });

    # Rotas dos usuários
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('index', ['middleware' => 'permission:user.select', 'as' => 'index', 'uses' => 'UserController@index']);
        Route::get('grid', ['middleware' => 'permission:user.select', 'as' => 'grid', 'uses' => 'UserController@grid']);
        Route::get('create', ['middleware' => 'permission:user.store', 'as' => 'create', 'uses' => 'UserController@create']);
        Route::post('store', ['middleware' => 'permission:user.store', 'as' => 'store', 'uses' => 'UserController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:user.update', 'as' => 'edit', 'uses' => 'UserController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:user.update', 'as' => 'update', 'uses' => 'UserController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:user.destroy', 'as' => 'destroy', 'uses' => 'UserController@destroy']);

            # Rotas usuários > alterar senha
            Route::get('alterarSenha', ['as' => 'alterarSenha', 'uses' => 'UserController@alterarSenha']);
            Route::post('searchSenha', ['as' => 'searchSenha', 'uses' => 'UserController@searchSenha']);
            Route::post('novaSenha', ['as' => 'novaSenha', 'uses' => 'UserController@novaSenha']);
            Route::post('atualizarSenha', ['as' => 'atualizarSenha', 'uses' => 'UserController@atualizarSenha']);
    });

    # Rotas dos perfís
    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('index', ['middleware' => 'permission:role.select', 'as' => 'index', 'uses' => 'RoleController@index']);
        Route::get('grid', ['middleware' => 'permission:role.select', 'as' => 'grid', 'uses' => 'RoleController@grid']);

app/Http/Controllers/Relatorios/Alunos/FixaDoAlunoController.php
<?php

namespace SerEducacional\Http\Controllers\Relatorios\Alunos;

use Illuminate\Http\Request;

use SerEducacional\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use SerEducacional\Http\Requests;
use Yajra\Datatables\Datatables;
use SerEducacional\Uteis\GerarPDF;


class FixaDoAlunoController extends Controller
{

    /**
     * @param $alunoId
     */
    public function index($alunoId)
    {

        $dados = $this->dados($alunoId);

        // Retorno do template e dados do documento
        $view = \View::make("relatorios.alunos.views.fixadoaluno", compact('dados'));

        $view_content = $view->render();

        $pdf = new GerarPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        $urlImagemTopo = base_path("/public/img/logo_redape_igarassu.png");
        $urlImagemRodape = base_path("/public/img/logo_redape_igarassu.png");

        // Setando os parametros dinâmicos para montar o calendário
        //$pdf->setTitulo("FIXA DO ALUNO");
        $pdf->setUrlImagemTopo($urlImagemTopo);
        $pdf->setUrlImagemRodape($urlImagemRodape);

        $pdf->SetAuthor('Nicola Asuni');
        $pdf->SetTitle('Fixa do aluno');
        $pdf->SetSubject('');
        $pdf->SetKeywords('TCPDF, PDF, example, test, guide');

        // set default header data
        $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

        // set header and footer fonts
        $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // set margins
        $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

        $pdf->SetFont('dejavusans', '', 9, '', true);

        $pdf->AddPage();

        $pdf->writeHTML($view_content, true, false, true, false, '');

        $pdf->Output('fixa_do_aluno.pdf');
    }


    /**
     * @param $alunoId
     */
    public function dados($alunoId)
    {

        $aluno = \DB::table('edu_alunos')
            ->leftJoin('gen_cgm', 'gen_cgm.id', '=', 'edu_alunos.cgm_id')
            ->leftJoin('gen_endereco', 'gen_endereco.id', '=', 'gen_cgm.endereco_id')
            ->leftJoin('gen_bairros', 'gen_bairros.id', '=', 'gen_endereco.bairro_id')
            ->leftJoin('gen_cidades', 'gen_cidades.id', '=', 'gen_bairros.cidades_id')
            ->leftJoin('gen_estados', 'gen_estados.id', '=', 'gen_cidades.estados_id')
            ->leftJoin('gen_estado_civil', 'gen_estado_civil.id', '=', 'gen_cgm.estado_civil_id')
            ->leftJoin('gen_sexo', 'gen_sexo.id', '=', 'gen_cgm.sexo_id')
            ->leftJoin('gen_nacionalidade', 'gen_nacionalidade.id', '=', 'gen_cgm.nacionalidade_id')
            ->where('edu_alunos.id', $alunoId)
            ->select([
                'edu_alunos.codigo',
                'gen_cgm.nome',
                'gen_cgm.pai',
                'gen_cgm.mae',
                \DB::raw('DATE_FORMAT(gen_cgm.data_nascimento,"%d/%m/%Y") as data_nascimento'),
                'gen_estado_civil.nome as estado_civil',
                'gen_sexo.nome as sexo',
                'gen_nacionalidade.nome as nacionalidade',
                'gen_cgm.naturalidade',
                'gen_cgm.email',
                'gen_cgm.fone',
                'gen_cgm.fone2',
                \DB::raw('DATE_FORMAT(gen_cgm.data_cadastramento,"%d/%m/%Y") as data_cadastramento'),

                'gen_endereco.logradouro',
                'gen_endereco.numero',
                'gen_endereco.complemento',
                'gen_endereco.cep',
                'gen_bairros.nome as bairro',
                'gen_cidades.nome as cidade',
                'gen_estados.nome as estado',

                'gen_cgm.cpf',
                'gen_cgm.rg',
                'gen_cgm.numero_nis',
            ])->first();

        return $aluno;
    }
}

resources/views/aluno/create.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <section id="content">
            {{-- Mensagem de alerta quando os dados não atendem as regras de validação que foramd efinidas no servidor --}}
            <div class="ibox-content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif
            </div>
            {{-- Fim mensagem de alerta --}}
            {{--Formulario--}}
            {!! Form::open(['route'=>'aluno.store', 'id' => 'formAluno', 'method' => "POST" ]) !!}
            @include('tamplatesForms.tamplateFormAluno')
            {!! Form::close() !!}
            {{--Fim formulario--}}
        </section>
    </div>
@stop

resources/views/aluno/edit.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <br>
        <div class="ibox-content">

            <section id="content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                {!! Form::model($model, ['route'=> ['aluno.update', $model->id], 'id' => 'formAluno', 'method' => "POST" ]) !!}
                @include('tamplatesForms.tamplateFormAluno')
                {!! Form::close() !!}
            </section>
        </div>
    </div>
@stop

resources/views/aluno/index.blade.php
@extends('menu')

@section('css')
    <style>
        table#dados-turma tbody tr, table#dados-turma  thead tr {
            font-size: 11px;
        }
    </style>
@endsection

@section('content')
    <section id="content">
        <div class="container">
            <div class="block-header">
                <h2>Listar Alunos</h2>
            </div>

            <div class="card material-table">
                <div class="card-header">
                    @if(Session::has('message'))
                        <div class="alert alert-success">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <em> {!! session('message') !!}</em>
                        </div>
                    @endif

                    @if(Session::has('errors'))
                        <div class="alert alert-danger">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            @foreach($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                        </div>
                    @endif

                    @permission('aluno.store')
                    <!-- Botão novo -->
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="text-right">
                                <a class="btn btn-primary btn-sm m-t-10" href="{{ route('aluno.create') }}">Novo Aluno</a>
                            </div>
                        </div>
                    </div>
                    <!-- Botão novo -->
                    @endpermission
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="aluno-grid" class="table table-hover compact">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Codigo</th>
                                    <th>Data de Nascimento</th>
                                    <th>Nome da Mãe</th>
                                    <th>Açao</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Codigo</th>
                                    <th>Data de Nascimento</th>
                                    <th>Nome da Mãe</th>
                                    <th>Açao</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingOne">
                                        <h4 class="panel-title">
                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                                Relatórios de Alunos
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="form-group col-md-12">
                                                    <select class="form-control" id="report_id" name="relatorios">
                                                        <option value="">Selecione um relatório</option>
                                                        <option value="1">Fixa do aluno</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>

    @include('aluno.modal_adicionar_aluno_turma')
    @include('aluno.modal_historico')
    @include('aluno.modal_mudanca_turma')
    @include('relatorios.alunos.modals.modal_report_fixa_do_aluno')
@stop

@section('javascript')
    <script type="text/javascript" src="{{ asset('/dist/alunoTurma/loadFields.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/alunoTurma/modal_controller_aluno_turma.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/alunoTurma/modal_adicionar_aluno_turma.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/alunoTurma/modal_historico_aluno.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/alunoTurma/modal_mudanca_turma.js') }}"></script>

    <script type="text/javascript" src="{{ asset('/dist/relatorios/alunos/chamar_relatorios.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/relatorios/alunos/loadFields.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/relatorios/alunos/modal_fixa_do_aluno.js') }}"></script>

    <script type="text/javascript">
        var table = $('#aluno-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('aluno.grid') }}",
            columns: [
                {data: 'nome', name: 'gen_cgm.nome'},
                {data: 'codigo', name: 'edu_alunos.codigo'},
                {data: 'data_nascimento', name: 'gen_cgm.data_nascimento'},
                {data: 'mae', name: 'gen_cgm.mae'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

        // Geriamento dos relatórios avançadas
        $(document).on('change', '#report_id', function () {
            // Recuperando o id do relatório
            var reportId = $('#report_id').val();

            // Validando o id do relatório
            if(!reportId) {
                return false;
            }

            // Chama o modal do relatórios correspondente
            chamarRelatorio(reportId);

        });

    </script>
@stop

resources/views/aluno/modal_adicionar_aluno_turma.blade.php
<!-- Modal de cadastro das Alocações-->
<div id="modal-adicionar-aluno-turma" class="modal fade modal-profile" role="dialog" aria-labelledby="modalProfile" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width: 90%">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Matricular Aluno</h4>
            </div>
            <div class="modal-body" style="alignment-baseline: central">
                <div class="row" style="margin-bottom: 5%;">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12" style="background-color: #e6e9dc">
                                <div class="col-md-4" style="margin-top: 17px">
                                    <span><strong>Nome: </strong><p id="aNome"></p></span>
                                </div>

                                <div class="col-md-2" style="margin-top: 17px">
                                    <span><strong>Código: </strong><p id="aCodigo"></p></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" style="margin-top: 2%;">

                    <!-- Gerendiamento dos Alocações -->
                    <div class="col-md-12">
                        <!-- Adicionar Alocações -->
                        <div class="row">
                            <div class="col-md-12">

                                <div class="form-group col-md-2">
                                    <div class=" fg-line">
                                        <label for="turma">Turma *</label>
                                        <div class="select">
                                            {!! Form::select("turma", array(), null, array('class'=> 'form-control', 'id' => 'turma')) !!}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group col-md-2">
                                    <div class="fg-line">
                                        <label for="serie-historico">Série</label>
                                        <input type="text" class="form-control" id="serie-historico" readonly>
                                    </div>
                                </div>

                                <div class="form-group col-md-2">
                                    <div class="fg-line">
                                        <label for="turno-historico">Turno</label>
                                        <input type="text" class="form-control" id="turno-historico" readonly>
                                    </div>
                                </div>

                                <div class="form-group col-md-2">
                                    <div class="fg-line">
                                        <label for="vagas-historico">Vagas</label>
                                        <input type="text" class="form-control" id="vagas-historico" readonly>
                                    </div>
                                </div>

                                <div class="form-group col-md-2">
                                    <div class="fg-line">
                                        <label for="matriculados-historico">Alunos Matriculados</label>
                                        <input type="text" class="form-control" id="matriculados-historico" readonly>
                                    </div>
                                </div>

                                <div class="form-group col-md-2">
                                    <div class="fg-line">
                                        <label for="vagas-restantes-historico">Vagas restantes</label>
                                        <input type="text" class="form-control" id="vagas-restantes-historico" readonly>
                                    </div>
                                </div>

                                {{--<div class="form-group col-md-4">
                                    <div class="fg-line">
                                        <label for="data">Data da matrícula *</label>
                                        {!! Form::text('data', null, array('class' => 'form-control input-sm date-picker', 'id' => 'data', 'placeholder' => 'Data da matrícula')) !!}
                                    </div>
                                </div>--}}

                                <div class="form-group col-md-2">
                                    <div class="fg-line" style="margin-top: 10px">
                                        <button type="button" id="addAlunoTurma" class="btn btn-primary btn-sm m-t-10">Matricular</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- Fim Adicionar Alocações -->
                    </div>
                    <div class="col-md-12">
                        <!-- Table de Alocações -->
                        <div class="table-responsive">
                            <table id="aluno-turmas-grid" class="display table table-bordered" cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th>Matrícula</th>
                                    <th>Data</th>
                                    <th>Turma</th>
                                    <th>Escola</th>
                                    <th>Curso</th>
                                    <th>Base Curricular</th>
                                    <th>Calendário</th>
                                    <th>Série/Ano</th>
                                    <th>Turno</th>
                                    <th style="width: 8%;">Acão</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- Fim Table de alocações -->
                    </div>
                    <!-- Fim do Gerendiamento dos alocações -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FIM Modal de cadastro dos alocações-->