routes/web.php
    Route::group(['prefix' => 'calendario', 'as' => 'calendario.'], function () {
        Route::get('index', ['middleware' => 'permission:calendario.select', 'as' => 'index', 'uses' => 'CalendariosController@index']);
        Route::get('grid', ['middleware' => 'permission:calendario.select', 'as' => 'grid', 'uses' => 'CalendariosController@grid']);
        Route::get('create', ['middleware' => 'permission:calendario.store', 'as' => 'create', 'uses' => 'CalendariosController@create']);
        Route::post('store', ['middleware' => 'permission:calendario.store', 'as' => 'store', 'uses' => 'CalendariosController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:calendario.update', 'as' => 'edit', 'uses' => 'CalendariosController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:calendario.update', 'as' => 'update', 'uses' => 'CalendariosController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:calendario.destroy', 'as' => 'destroy', 'uses' => 'CalendariosController@destroy']);

        # rotas para períodos de avaliação
        Route::get('gridPeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'gridPeriodo', 'uses' => 'PeriodoAvaliacaosController@grid']);
        Route::post('getPeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'getPeriodo', 'uses' => 'PeriodoAvaliacaosController@getPeriodo']);
        Route::post('storePeriodo', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'storePeriodo', 'uses' => 'PeriodoAvaliacaosController@store']);
        Route::post('validarDataCalendario', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'validarDataCalendario', 'uses' => 'PeriodoAvaliacaosController@validarDataCalendario']);
        Route::post('updatePeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'updatePeriodo', 'uses' => 'PeriodoAvaliacaosController@update']);
        Route::post('removerPeriodo/{id}', ['middleware' => 'permission:calendario.add.periodo', 'as' => 'removerPeriodo', 'uses' => 'PeriodoAvaliacaosController@destroy']);

        # rotas para eventos
        Route::get('gridEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'gridEvento', 'uses' => 'EventosController@grid']);
        Route::post('getTipoEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getTipoEvento', 'uses' => 'EventosController@getTipoEvento']);
        Route::post('getDiaLetivo/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getDiaLetivo', 'uses' => 'EventosController@getDiaLetivo']);
        Route::post('storeEvento', ['middleware' => 'permission:calendario.add.evento', 'as' => 'storeEvento', 'uses' => 'EventosController@store']);
        Route::post('updateEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'updateEvento', 'uses' => 'EventosController@update']);
        Route::post('removerEvento/{id}', ['middleware' => 'permission:calendario.add.evento', 'as' => 'removerEvento', 'uses' => 'EventosController@destroy']);
        Route::post('getDiaSemana', ['middleware' => 'permission:calendario.add.evento', 'as' => 'getDiaSemana', 'uses' => 'EventosController@getDiaSemana']);
    });

    #Rotas das formas de avaliações
    Route::group(['prefix' => 'formaAvaliacao', 'as' => 'formaAvaliacao.'], function () {
        Route::get('index', ['middleware' => 'permission:forma.avaliacao.select', 'as' => 'index', 'uses' => 'FormaAvaliacoesController@index']);
        Route::get('grid', ['middleware' => 'permission:forma.avaliacao.select', 'as' => 'grid', 'uses' => 'FormaAvaliacoesController@grid']);
        Route::get('create', ['middleware' => 'permission:forma.avaliacao.store', 'as' => 'create', 'uses' => 'FormaAvaliacoesController@create']);
        Route::post('store', ['middleware' => 'permission:forma.avaliacao.store', 'as' => 'store', 'uses' => 'FormaAvaliacoesController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:forma.avaliacao.update', 'as' => 'edit', 'uses' => 'FormaAvaliacoesController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:forma.avaliacao.update', 'as' => 'update', 'uses' => 'FormaAvaliacoesController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:forma.avaliacao.destroy', 'as' => 'destroy', 'uses' => 'FormaAvaliacoesController@destroy']);

        # Rotas para niveis de alfabetizacao
        Route::get('nivelAlfabetizacao/grid/{id}', ['as' => 'nivelAlfabetizacao.grid', 'uses' => 'FormaAvaliacoesController@gridNiveis']);
        Route::post('nivelAlfabetizacao/store', ['as' => 'nivelAlfabetizacao.store', 'uses' => 'FormaAvaliacoesController@storeNivel']);
        Route::post('nivelAlfabetizacao/destroy/{id}', ['as' => 'nivelAlfabetizacao.destroy', 'uses' => 'FormaAvaliacoesController@destroyNivel']);
    });

    # Rotas do aluno
    Route::group(['prefix' => 'aluno', 'as' => 'aluno.'], function () {
        Route::get('index', ['middleware' => 'permission:aluno.select', 'as' => 'index', 'uses' => 'AlunoController@index']);
        Route::get('grid', ['middleware' => 'permission:aluno.select', 'as' => 'grid', 'uses' => 'AlunoController@grid']);
        Route::get('create', ['middleware' => 'permission:aluno.store', 'as' => 'create', 'uses' => 'AlunoController@create']);
        Route::post('store', ['middleware' => 'permission:aluno.store', 'as' => 'store', 'uses' => 'AlunoController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:aluno.update', 'as' => 'edit', 'uses' => 'AlunoController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:aluno.update', 'as' => 'update', 'uses' => 'AlunoController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:aluno.destroy', 'as' => 'destroy', 'uses' => 'AlunoController@destroy']);

        Route::get('getImgAluno/{id}', ['as' => 'getImgAluno', 'uses' => 'AlunoController@getImgAluno']);

        Route::post('findBairro', ['as' => 'findBairro', 'uses' => 'AlunoController@findBairro']);
        Route::post('findCidade', ['as' => 'findCidade', 'uses' => 'AlunoController@findCidade']);
        Route::post('searchCpf', ['as' => 'searchCpf', 'uses' => 'AlunoController@searchCpf']);

        # rotas para alunos turmas
        Route::get('gridAlunoTurma/{id}', ['middleware' => 'permission:aluno.matricula', 'as' => 'gridAlunoTurma', 'uses' => 'AlunoTurmasController@grid']);
        Route::post('getTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'getTurma', 'uses' => 'AlunoTurmasController@getTurma']);
        Route::post('getTurmaMudanca', ['as' => 'getTurmaMudanca', 'uses' => 'AlunoTurmasController@getTurmaMudanca']);
        Route::post('storeAlunoTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'storeAlunoTurma', 'uses' => 'AlunoTurmasController@store']);
        Route::post('getDadosTurma', ['middleware' => 'permission:aluno.matricula', 'as' => 'getDadosTurma', 'uses' => 'AlunoTurmasController@getDadosTurma']);
        Route::post('storeMudarTurma', ['as' => 'storeMudarTurma', 'uses' => 'AlunoTurmasController@storeMudarTurma']);
        //Route::post('updateTelefone/{id}', ['as' => 'updateTelefone', 'uses' => 'TelefonesController@update']);
       //Route::post('removerTelefone/{id}', ['as' => 'removerTelefone', 'uses' => 'TelefonesController@destroy']);
    });

    # Rotas dos tipos de eventos
    Route::group(['prefix' => 'tipoEvento', 'as' => 'tipoEvento.'], function () {
        Route::get('index', ['middleware' => 'permission:tipo.evento.select', 'as' => 'index', 'uses' => 'TipoEventosController@index']);
        Route::get('grid', ['middleware' => 'permission:tipo.evento.select', 'as' => 'grid', 'uses' => 'TipoEventosController@grid']);
        Route::get('create', ['middleware' => 'permission:tipo.evento.store', 'as' => 'create', 'uses' => 'TipoEventosController@create']);
        Route::post('store', ['middleware' => 'permission:tipo.evento.store', 'as' => 'store', 'uses' => 'TipoEventosController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:tipo.evento.update', 'as' => 'edit', 'uses' => 'TipoEventosController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:tipo.evento.update', 'as' => 'update', 'uses' => 'TipoEventosController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:tipo.evento.destroy', 'as' => 'destroy', 'uses' => 'TipoEventosController@destroy']);
    });

    # Rotas dos perídos de avaliação
    Route::group(['prefix' => 'periodo', 'as' => 'periodo.'], function () {
        Route::get('index', ['middleware' => 'permission:periodo.select', 'as' => 'index', 'uses' => 'PeriodoController@index']);
        Route::get('grid', ['middleware' => 'permission:periodo.select', 'as' => 'grid', 'uses' => 'PeriodoController@grid']);
        //Route::get('grid', ['middleware' => 'permission:periodo.select', 'as' => 'grid', 'uses' => 'PeriodoController@grid']);
        Route::get('create', ['middleware' => 'permission:periodo.store', 'as' => 'create', 'uses' => 'PeriodoController@create']);
        Route::post('store', ['middleware' => 'permission:periodo.store', 'as' => 'store', 'uses' => 'PeriodoController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:periodo.update', 'as' => 'edit', 'uses' => 'PeriodoController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:periodo.update', 'as' => 'update', 'uses' => 'PeriodoController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:periodo.destroy', 'as' => 'destroy', 'uses' => 'PeriodoController@destroy']);
    });

    # Rotas dos usuários
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('index', ['middleware' => 'permission:user.select', 'as' => 'index', 'uses' => 'UserController@index']);

resources/views/formaAvaliacao/create.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <section id="content">
            {{-- Mensagem de alerta quando os dados não atendem as regras de validação que foramd efinidas no servidor --}}
            <div class="ibox-content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif
            </div>
            {{-- Fim mensagem de alerta --}}

            {{--Formulario--}}
            {!! Form::open(['route'=>'formaAvaliacao.store', 'id' => 'formFormaAvaliacao', 'method' => "POST" ]) !!}
                @include('tamplatesForms.tamplateFormFormaAvaliacao')
            {!! Form::close() !!}
            {{--Fim formulario--}}
        </section>
    </div>
@stop

resources/views/formaAvaliacao/edit.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <br>
        <div class="ibox-content">

            <section id="content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                {!! Form::model($model, ['route'=> ['formaAvaliacao.update', $model->id], 'id' => 'formFormaAvaliacao', 'method' => "POST" ]) !!}
                    @include('tamplatesForms.tamplateFormFormaAvaliacao')
                {!! Form::close() !!}
            </section>
        </div>
    </div>
@stop

resources/views/formaAvaliacao/index.blade.php
@extends('menu')

@section('content')
    <section id="content">
        <div class="container">
            <div class="block-header">
                <h2>Listar Formas de Avaliações</h2>
            </div>

            <div class="card material-table">
                <div class="card-header">
                    @if(Session::has('message'))
                        <div class="alert alert-success">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <em> {!! session('message') !!}</em>
                        </div>
                    @endif

                    @if(Session::has('errors'))
                        <div class="alert alert-danger">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            @foreach($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                        </div>
                    @endif

                    @permission('forma.avaliacao.store')
                    <!-- Botão novo -->
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="text-right">
                                <a class="btn btn-primary btn-sm m-t-10", href="{{ route('formaAvaliacao.create') }}">Nova Forma de Avaliação</a>
                            </div>
                        </div>
                    </div>
                    <!-- Botão novo -->
                    @endpermission
                </div>

                <div class="table-responsive">
                    <table id="forma-avaliacao-grid" class="table table-hover">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Codigo</th>
                                <th>Tipo Resultado</th>
                                <th>Açao</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Codigo</th>
                                <th>Tipo Resultado</th>
                                <th style="width: 10%;">Açao</th>
                            </tr>
                            </tfoot>
                    </table>
                </div>
            </div>

        </div>
    </section>
@stop

@section('javascript')
    <script type="text/javascript">
        var table = $('#forma-avaliacao-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('formaAvaliacao.grid') }}",
            columns: [
                {data: 'nome', name: 'edu_formas_avaliacoes.nome'},
                {data: 'codigo', name: 'edu_formas_avaliacoes.codigo'},
                {data: 'tipo_resultado', name: 'edu_tipos_resultados.nome'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    </script>
@stop