routes/web.php
        Route::get('create', ['middleware' => 'permission:funcao.store', 'as' => 'create', 'uses' => 'FuncaoController@create']);
        Route::post('store', ['middleware' => 'permission:funcao.store', 'as' => 'store', 'uses' => 'FuncaoController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:funcao.update', 'as' => 'edit', 'uses' => 'FuncaoController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:funcao.update', 'as' => 'update', 'uses' => 'FuncaoController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:funcao.destroy', 'as' => 'destroy', 'uses' => 'FuncaoController@destroy']);
    });

    # Rotas de escola
    Route::group(['prefix' => 'escola', 'as' => 'escola.'], function () {
        Route::get('index', ['middleware' => 'permission:escola.select', 'as' => 'index', 'uses' => 'EscolaController@index']);
        Route::get('grid', ['middleware' => 'permission:escola.select', 'as' => 'grid', 'uses' => 'EscolaController@grid']);
        Route::get('create', ['middleware' => 'permission:escola.store', 'as' => 'create', 'uses' => 'EscolaController@create']);
        Route::post('store', ['middleware' => 'permission:escola.store', 'as' => 'store', 'uses' => 'EscolaController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:escola.update', 'as' => 'edit', 'uses' => 'EscolaController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:escola.update', 'as' => 'update', 'uses' => 'EscolaController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:escola.destroy', 'as' => 'destroy', 'uses' => 'EscolaController@destroy']);

        # Rotas para endereço
        Route::post('findBairro', ['as' => 'findBairro', 'uses' => 'EscolaController@findBairro']);
        Route::post('findCidade', ['as' => 'findCidade', 'uses' => 'EscolaController@findCidade']);

        # Rotas para cursos
        Route::get('curso/gridCursos/{id}', ['middleware' => 'permission:escola.add.curso', 'as' => 'curso.gridCursos', 'uses' => 'EscolaCursoController@gridCursos']);
        Route::post('curso/select2', ['middleware' => 'permission:escola.add.curso', 'as' => 'curso.select2', 'uses' => 'EscolaCursoController@cursosSelect2']);
        Route::post('curso/adicionarCursos', ['middleware' => 'permission:escola.add.curso', 'as' => 'curso.adicionarCursos', 'uses' => 'EscolaCursoController@adicionarCursos']);
        Route::post('curso/removerCurso/{idEscolaCurso}', ['middleware' => 'permission:escola.add.curso', 'as' => 'curso.removerCurso', 'uses' => 'EscolaCursoController@removerCurso']);

        # Rotas para turnos
        Route::get('turno/gridTurnos/{idEscolaCurso}', ['middleware' => 'permission:escola.add.curso', 'as' => 'turno.gridTurnos', 'uses' => 'EscolaCursoTurnoController@gridTurnos']);
        Route::post('turno/select2', ['middleware' => 'permission:escola.add.curso', 'as' => 'turno.select2', 'uses' => 'EscolaCursoTurnoController@turnosSelect2']);
        Route::post('turno/adicionarTurnos', ['middleware' => 'permission:escola.add.curso', 'as' => 'turno.adicionarTurnos', 'uses' => 'EscolaCursoTurnoController@adicionarTurnos']);
        Route::post('turno/removerTurno', ['middleware' => 'permission:escola.add.curso', 'as' => 'turno.removerTurno', 'uses' => 'EscolaCursoTurnoController@removerTurno']);
    });

    #Rotas servidor
    Route::group(['prefix' => 'servidor', 'as' => 'servidor.'], function () {
        Route::get('index', ['middleware' => 'permission:servidor.select', 'as' => 'index', 'uses' => 'ServidorController@index']);
        Route::get('grid', ['middleware' => 'permission:servidor.select', 'as' => 'grid', 'uses' => 'ServidorController@grid']);
        Route::get('create', ['middleware' => 'permission:servidor.store', 'as' => 'create', 'uses' => 'ServidorController@create']);
        Route::post('store', ['middleware' => 'permission:servidor.store', 'as' => 'store', 'uses' => 'ServidorController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:servidor.update', 'as' => 'edit', 'uses' => 'ServidorController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:servidor.update', 'as' => 'update', 'uses' => 'ServidorController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:servidor.destroy', 'as' => 'destroy', 'uses' => 'ServidorController@destroy']);
        //unique cpf
        Route::post('searchCpf', ['as' => 'searchCpf', 'uses' => 'ServidorController@searchCpf']);
        //Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'DisciplinasController@destroy']);

        # rotas para telefones
        Route::get('gridTelefone/{id}', ['middleware' => 'permission:servidor.add.telefone', 'as' => 'gridTelefone', 'uses' => 'TelefonesController@grid']);
        Route::post('getTipoTelefone', ['middleware' => 'permission:servidor.add.telefone', 'as' => 'getTipoTelefone', 'uses' => 'TelefonesController@getTipoTelefone']);
        Route::post('storeTelefone', ['middleware' => 'permission:servidor.add.telefone', 'as' => 'storeTelefone', 'uses' => 'TelefonesController@store']);
        Route::post('updateTelefone/{id}', ['middleware' => 'permission:servidor.add.telefone', 'as' => 'updateTelefone', 'uses' => 'TelefonesController@update']);
        Route::post('removerTelefone/{id}', ['middleware' => 'permission:servidor.add.telefone', 'as' => 'removerTelefone', 'uses' => 'TelefonesController@destroy']);

        # rotas para relação de trabalho
        Route::get('gridRelacao/{id}', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'gridRelacao', 'uses' => 'RelacaoTrabalhosController@grid']);
        Route::post('storeRelacao', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'storeRelacao', 'uses' => 'RelacaoTrabalhosController@store']);
        Route::post('updateRelacao/{id}', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'updateRelacao', 'uses' => 'RelacaoTrabalhosController@update']);
        Route::post('removerRelacao/{id}', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'removerRelacao', 'uses' => 'RelacaoTrabalhosController@destroy']);
        Route::post('getRegimes', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'getRegimes', 'uses' => 'RelacaoTrabalhosController@getRegimes']);
        Route::post('getAreas', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'getAreas', 'uses' => 'RelacaoTrabalhosController@getAreas']);
        Route::post('getEnsinos', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'getEnsinos', 'uses' => 'RelacaoTrabalhosController@getEnsinos']);
        Route::post('getDisciplinas', ['middleware' => 'permission:servidor.add.relacao.trabalho', 'as' => 'getDisciplinas', 'uses' => 'RelacaoTrabalhosController@getDisciplinas']);

        # rotas para formações
        Route::get('gridFormacao/{id}', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'gridFormacao', 'uses' => 'FormacaosController@grid']);
        Route::post('storeFormacao', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'storeFormacao', 'uses' => 'FormacaosController@store']);
        Route::post('updateFormacao/{id}', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'updateFormacao', 'uses' => 'FormacaosController@update']);
        Route::post('removerFormacao/{id}', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'removerFormacao', 'uses' => 'FormacaosController@destroy']);
        Route::post('getCursos', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getCursos', 'uses' => 'FormacaosController@getCursos']);
        Route::post('getInstituicoes', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getInstituicoes', 'uses' => 'FormacaosController@getInstituicoes']);
        Route::post('getSituacoes', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getSituacoes', 'uses' => 'FormacaosController@getSituacoes']);
        Route::post('getLicenciaturas', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getLicenciaturas', 'uses' => 'FormacaosController@getLicenciaturas']);
        Route::post('getPos', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getPos', 'uses' => 'FormacaosController@getPos']);
        Route::post('getOutrosCursos', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getOutrosCursos', 'uses' => 'FormacaosController@getOutrosCursos']);
        Route::post('edtOutrosCursos', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'edtOutrosCursos', 'uses' => 'FormacaosController@edtOutrosCursos']);
        Route::post('getPosOutrosCursos', ['middleware' => 'permission:servidor.add.formacao', 'as' => 'getPosOutrosCursos', 'uses' => 'FormacaosController@getPosOutrosCursos']);

        # rotas para atividades
        Route::get('gridAtividade/{id}', ['middleware' => 'permission:servidor.add.atividade', 'as' => 'gridAtividade', 'uses' => 'AtividadesController@grid']);
        Route::post('storeAtividade', ['middleware' => 'permission:servidor.add.atividade', 'as' => 'storeAtividade', 'uses' => 'AtividadesController@store']);
        Route::post('updateAtividade/{id}', ['middleware' => 'permission:servidor.add.atividade', 'as' => 'updateAtividade', 'uses' => 'AtividadesController@update']);
        Route::post('removerAtividade/{id}', ['middleware' => 'permission:servidor.add.atividade', 'as' => 'removerAtividade', 'uses' => 'AtividadesController@destroy']);
        Route::post('getFuncoes', ['middleware' => 'permission:servidor.add.atividade', 'as' => 'getFuncoes', 'uses' => 'AtividadesController@getFuncoes']);

        # rotas para alocações
        Route::get('gridAlocacao/{id}', ['middleware' => 'permission:servidor.add.alocacao', 'as' => 'gridAlocacao', 'uses' => 'AlocacaosController@grid']);

resources/views/servidor/create.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <section id="content">
            {{-- Mensagem de alerta quando os dados não atendem as regras de validação que foramd efinidas no servidor --}}
            <div class="ibox-content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif
            </div>
            {{-- Fim mensagem de alerta --}}
            {{--Formulario--}}
            {!! Form::open(['route'=>'servidor.store', 'id' => 'formServidor', 'method' => "POST" ]) !!}
            @include('tamplatesForms.tamplateFormServidor')
            {!! Form::close() !!}
            {{--Fim formulario--}}
        </section>
    </div>
@stop

resources/views/servidor/edit.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <br>
        <div class="ibox-content">

            <section id="content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                {!! Form::model($model, ['route'=> ['servidor.update', $model->id], 'id' => 'formServidor', 'method' => "POST" ]) !!}
                @include('tamplatesForms.tamplateFormServidor')
                {!! Form::close() !!}
            </section>
        </div>
    </div>
@stop

resources/views/servidor/index.blade.php
@extends('menu')

@section('content')
    <section id="content">
        <div class="container">
            <div class="block-header">
                <h2>Listar Servidores</h2>
            </div>

            <div class="card material-table">
                <div class="card-header">
                    @if(Session::has('message'))
                        <div class="alert alert-success">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <em> {!! session('message') !!}</em>
                        </div>
                    @endif

                    @if(Session::has('errors'))
                        <div class="alert alert-danger">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            @foreach($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                        </div>
                    @endif

                    @permission('servidor.store')
                    <!-- Botão novo -->
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="text-right">
                                <a class="btn btn-primary btn-sm m-t-10", href="{{ route('servidor.create') }}">Novo Servidor</a>
                            </div>
                        </div>
                    </div>
                    <!-- Botão novo -->
                    @endpermission
                </div>

                <div class="table-responsive">
                    <table id="servidor-grid" class="table table-hover">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Matrícula</th>
                                <th>Açao</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Matrícula</th>
                                <th style="width: 12%;">Açao</th>
                            </tr>
                            </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </section>

    @include('servidor.modal_adicionar_telefones')
    @include('servidor.modal_adicionar_relacao_trabalho')
    @include('servidor.modal_adicionar_formacao')
    @include('servidor.modal_adicionar_atividade')
    @include('servidor.modal_adicionar_alocacao')
    @include('servidor.modal_adicionar_disponibilidade')
@stop

@section('javascript')
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_controller_servidor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_telefones.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_relacao_trabalho.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_formacao.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_atividade.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_alocacao.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/modal_adicionar_disponibilidade.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/loadFields.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/servidor/loadFieldsDisponibilidade.js') }}"></script>
    <script type="text/javascript">
        var table = $('#servidor-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route ('servidor.grid') }}",
            columns: [
                {data: 'nome', name: 'gen_cgm.nome'},
                {data: 'matricula', name: 'edu_servidor.matricula'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ],
        });

        // Máscaras
        $(document).ready(function() {
            $('#numero').mask('(00) 00000-0000');
        });
    </script>
@stop

resources/views/servidor/modal_adicionar_alocacao.blade.php
<!-- Modal de cadastro das Alocações-->
<div id="modal-adicionar-alocacoes" class="modal fade modal-profile" role="dialog" aria-labelledby="modalProfile" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width: 90%">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Adicionar Alocações</h4>
            </div>
            <div class="modal-body" style="alignment-baseline: central">
                <div class="row" style="margin-bottom: 5%;">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12" style="background-color: #e6e9dc">
                                <div class="col-md-4" style="margin-top: 17px">
                                    <span><strong>Nome: </strong><p class="sNome"></p></span>
                                </div>

                                <div class="col-md-2" style="margin-top: 17px">
                                    <span><strong>Matrícula: </strong><p class="sMatricula"></p></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row" style="margin-top: 2%;">

                    <!-- Gerendiamento dos Alocações -->
                    <div class="col-md-12">
                        <!-- Adicionar Alocações -->
                        <div class="row" style="margin-top: -2%; margin-bottom: 3%;">
                            <div class="form-group col-md-4">
                                <div class=" fg-line">
                                    <label for="escola">Escola *</label>
                                    {!! Form::select("escola", array(), null, array('class'=> 'form-control', 'id' => 'escola')) !!}
                                </div>
                            </div>

                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <label for="carga-horaria">Carga horária *</label>
                                    {!! Form::text('carga-horaria', null,
                                       array('class' => 'form-control', 'id' => 'carga-horaria')) !!}
                                </div>
                            </div>

                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <label for="carga-horaria-disp">Carga horária disponível</label>
                                    {!! Form::text('carga_horaria_disp', null,
                                       array('class' => 'form-control', 'id' => 'carga-horaria-disp', 'readonly' => 'readonly')) !!}
                                </div>
                            </div>

                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <label for="carga-horaria-total">Carga horária total</label>
                                    {!! Form::text('carga_horaria_total', null,
                                       array('class' => 'form-control', 'id' => 'carga-horaria-total','readonly' => 'readonly')) !!}
                                </div>
                            </div>

                            <div class="form-group col-md-2">
                                <div class="fg-line" style="margin-top: 20px">
                                    <div class="fg-line">
                                        <button type="button"   id="addAlocacao" class="btn btn-primary btn-sm m-t-10">Adicionar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Fim Adicionar Alocações -->

                        <!-- Table de Alocações -->
                        <div class="table-responsive">
                            <table id="alocacoes-grid" class="display table table-bordered" cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th>Escola</th>
                                    <th>Carga Horaria Alocada</th>
                                    <th style="width: 8%;">Acão</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- Fim Table de alocações -->
                    </div>
                    <!-- Fim do Gerendiamento dos alocações -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FIM Modal de cadastro dos alocações-->

resources/views/servidor/modal_adicionar_atividade.blade.php
<!-- Modal de cadastro das atividades-->
<div id="modal-adicionar-atividades" class="modal fade modal-profile" role="dialog" aria-labelledby="modalProfile" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width: 90%">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Adicionar Atividades</h4>
            </div>
            <div class="modal-body" style="alignment-baseline: central">
                <div class="row" style="margin-bottom: 5%;">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12" style="background-color: #e6e9dc">
                                <div class="col-md-4" style="margin-top: 17px">
                                    <span><strong>Nome: </strong><p class="sNome"></p></span>
                                </div>

                                <div class="col-md-2" style="margin-top: 17px">
                                    <span><strong>Matrícula: </strong><p class="sMatricula"></p></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row" style="margin-top: 2%;">

                    <!-- Gerendiamento dos atividades -->
                    <div class="col-md-12">
                        <!-- Adicionar atividades -->
                        <div class="row" style="margin-top: -2%; margin-bottom: 3%;">
                            <div class="form-group col-md-2">
                                <div class=" fg-line">
                                    <label for="funcao">Atividade *</label>
                                    <div class="select">
                                        {!! Form::select("funcao", array(), null, array('class'=> 'form-control', 'id' => 'funcao')) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <div class="fg-line">
                                        <label for="horaManha">Horas Manhã *</label>
                                        {!! Form::text('horaManha', null, array('class' => 'form-control input-sm', 'id' => 'horaManha', 'placeholder' => 'Horas Manhã')) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <div class="fg-line">
                                        <label for="horaTarde">Horas Tarde</label>
                                        {!! Form::text('horaTarde', null, array('class' => 'form-control input-sm', 'id' => 'horaTarde', 'placeholder' => 'Horas Tarde')) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                <div class="fg-line">
                                    <div class="fg-line">
                                        <label for="horaNoite">Horas Noite</label>
                                        {!! Form::text('horaNoite', null, array('class' => 'form-control input-sm', 'id' => 'horaNoite', 'placeholder' => 'Horas Noite')) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                <div class="fg-line" style="margin-top: 20px">
                                    <div class="fg-line">
                                        <button type="button" id="addAtividade" class="btn btn-primary btn-sm m-t-10">Adicionar</button>
                                        <button style="margin-left: 5px" type="button" id="edtAtividade" class="btn btn-success btn-sm m-t-10">Editar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Fim Adicionar atividades -->

                        <!-- Table de atividades -->
                        <div class="table-responsive">
                            <table id="atividades-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th>Atividade</th>
                                    <th>Hora Manhã</th>
                                    <th>Hora Tarde</th>
                                    <th>Hora Noite</th>
                                    <th style="width: 8%;">Acão</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- Fim Table de atividades -->
                    </div>
                    <!-- Fim do Gerendiamento dos atividades -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FIM Modal de cadastro dos atividades-->