routes/web.php
            Route::post('validarprofessor', ['as' => 'validarprofessor', 'uses' => 'HorariosController@validarProfessores']);
        });

        # Modal de matricula
        Route::group(['prefix' => 'historico', 'as' => 'historico.'], function () {
            Route::get('gridAlunos/{idTurma}', ['as' => 'gridAlunos', 'uses' => 'HistoricoController@gridAlunos']);
            Route::post('getTurma', ['as' => 'getTurma', 'uses' => 'HistoricoController@getTurma']);
            Route::post('getSerie', ['as' => 'getSerie', 'uses' => 'HistoricoController@getSerie']);
            Route::post('getDadosTurma', ['as' => 'getDadosTurma', 'uses' => 'HistoricoController@getDadosTurma']);
            Route::post('store', ['as' => 'store', 'uses' => 'HistoricoController@store']);
            //Route::post('adicionarParecer', ['as' => 'adicionarParecer', 'uses' => 'TurmaParecerController@adicionarParecer']);
            //Route::post('removerParecer', ['as' => 'removerParecer', 'uses' => 'TurmaParecerController@removerParecer']);
        });

        # Modal de concelho pedagógico
        Route::group(['prefix' => 'concelho', 'as' => 'concelho.'], function () {
            Route::get('grid/{id}', ['as' => 'grid', 'uses' => 'ConcelhoPedagogicoController@grid']);
            Route::post('store', ['as' => 'store', 'uses' => 'ConcelhoPedagogicoController@store']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ConcelhoPedagogicoController@update']);
            Route::post('remover/{id}', ['as' => 'remover', 'uses' => 'ConcelhoPedagogicoController@destroy']);
            Route::post('getPeriodos', ['as' => 'getPeriodos', 'uses' => 'ConcelhoPedagogicoController@getPeriodos']);
        });

        # rotas para atribuição de notas
        Route::group(['prefix' => 'nota', 'as' => 'nota.'], function () {
            Route::get('index/{idTurma}', ['as' => 'index', 'uses' => 'NotaController@index']);
            Route::post('consultar', ['as' => 'consultar', 'uses' => 'NotaController@consultar']);
            Route::post('store', ['as' => 'store', 'uses' => 'NotaController@store']);
        });

        # rotas para atribuição de notas
        Route::group(['prefix' => 'notabydisciplina', 'as' => 'notabydisciplina.'], function () {
            Route::get('index/{idTurma}', ['as' => 'index', 'uses' => 'NotaByDisciplinasController@index']);
            Route::post('consultar', ['as' => 'consultar', 'uses' => 'NotaByDisciplinasController@consultar']);
            Route::post('store', ['as' => 'store', 'uses' => 'NotaByDisciplinasController@store']);
        });

        # rotas para atribuição de notas por parecer
        Route::group(['prefix' => 'notaparecer', 'as' => 'notaparecer.'], function () {
            Route::get('index/{idTurma}', ['as' => 'index', 'uses' => 'NotaParecerController@index']);
            Route::post('consultar', ['as' => 'consultar', 'uses' => 'NotaParecerController@consultar']);
            Route::post('store', ['as' => 'store', 'uses' => 'NotaParecerController@store']);
        });

        # rotas para atribuição de frequência
        Route::group(['prefix' => 'frequencia', 'as' => 'frequencia.'], function () {
            Route::get('index/{idTurma}', ['as' => 'index', 'uses' => 'FrequenciaController@index']);
            Route::post('getDisciplinas', ['as' => 'getDisciplinas', 'uses' => 'FrequenciaController@getDisciplinas']);
            Route::post('consultar', ['as' => 'consultar', 'uses' => 'FrequenciaController@consultar']);
            Route::post('store', ['as' => 'store', 'uses' => 'FrequenciaController@store']);
        });

        # rotas para atribuição de frequência simples
        Route::group(['prefix' => 'frequenciasimples', 'as' => 'frequenciasimples.'], function () {
            Route::get('index/{idTurma}', ['as' => 'index', 'uses' => 'FrequenciaSimplesController@index']);
            Route::post('consultar', ['as' => 'consultar', 'uses' => 'FrequenciaSimplesController@consultar']);
            Route::post('store', ['as' => 'store', 'uses' => 'FrequenciaSimplesController@store']);
        });

    });

    # Rotas das turmas complementares
    Route::group(['prefix' => 'turmaComplementar', 'as' => 'turmaComplementar.'], function () {
        Route::get('index', ['middleware' => 'permission:turma.complementar.select', 'as' => 'index', 'uses' => 'TurmaComplementarController@index']);
        Route::get('grid', ['middleware' => 'permission:turma.complementar.select', 'as' => 'grid', 'uses' => 'TurmaComplementarController@grid']);
        Route::get('create', ['middleware' => 'permission:turma.complementar.store', 'as' => 'create', 'uses' => 'TurmaComplementarController@create']);
        Route::post('store', ['middleware' => 'permission:turma.complementar.store', 'as' => 'store', 'uses' => 'TurmaComplementarController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:turma.complementar.update', 'as' => 'edit', 'uses' => 'TurmaComplementarController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:turma.complementar.update', 'as' => 'update', 'uses' => 'TurmaComplementarController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:turma.complementar.destroy', 'as' => 'destroy', 'uses' => 'TurmaComplementarController@destroy']);

        # Modal de atividades
        Route::group(['prefix' => 'atividade', 'as' => 'atividade.'], function () {
            Route::get('grid/{idTurmaComplementar}', ['middleware' => 'permission:turma.complementar.add.atividade', 'as' => 'grid', 'uses' => 'TurmaComplementarAtividadeController@grid']);
            Route::post('select2', ['middleware' => 'permission:turma.complementar.add.atividade', 'as' => 'select2', 'uses' => 'TurmaComplementarAtividadeController@atividadeSelect2']);
            Route::post('adicionarAtividade', ['middleware' => 'permission:turma.complementar.add.atividade', 'as' => 'adicionarAtividade', 'uses' => 'TurmaComplementarAtividadeController@adicionarAtividade']);
            Route::post('removerAtividade', ['middleware' => 'permission:turma.complementar.add.atividade', 'as' => 'removerAtividade', 'uses' => 'TurmaComplementarAtividadeController@removerAtividade']);
        });

        # Modal de alunos
        Route::group(['prefix' => 'aluno', 'as' => 'aluno.'], function () {
            Route::get('grid/{idTurmaComplementar}', ['middleware' => 'permission:turma.complementar.add.aluno', 'as' => 'grid', 'uses' => 'TurmaComplementarAlunoController@grid']);
            Route::post('select2', ['middleware' => 'permission:turma.complementar.add.aluno', 'as' => 'select2', 'uses' => 'TurmaComplementarAlunoController@alunosSelect2']);
            Route::post('findNumAlunosMatriculados/{idTurmaComplementar}', ['middleware' => 'permission:turma.complementar.add.aluno', 'as' => 'findNumAlunosMatriculados', 'uses' => 'TurmaComplementarAlunoController@findNumAlunosMatriculados']);
            Route::post('adicionarAtividade', ['middleware' => 'permission:turma.complementar.add.aluno', 'as' => 'adicionarAluno', 'uses' => 'TurmaComplementarAlunoController@adicionarAluno']);
            Route::post('removerAtividade', ['middleware' => 'permission:turma.complementar.add.aluno', 'as' => 'removerAluno', 'uses' => 'TurmaComplementarAlunoController@removerAluno']);
        });

    });

    # Rotas de pareceres
    Route::group(['prefix' => 'parecer', 'as' => 'parecer.'], function () {
        Route::get('index', ['middleware' => 'permission:parecer.select', 'as' => 'index', 'uses' => 'ParecerController@index']);
        Route::get('grid', ['middleware' => 'permission:parecer.select', 'as' => 'grid', 'uses' => 'ParecerController@grid']);
        Route::get('create', ['middleware' => 'permission:parecer.store', 'as' => 'create', 'uses' => 'ParecerController@create']);
        Route::post('store', ['middleware' => 'permission:parecer.store', 'as' => 'store', 'uses' => 'ParecerController@store']);
        Route::get('edit/{id}', ['middleware' => 'permission:parecer.update', 'as' => 'edit', 'uses' => 'ParecerController@edit']);
        Route::post('update/{id}', ['middleware' => 'permission:parecer.update', 'as' => 'update', 'uses' => 'ParecerController@update']);
        Route::get('destroy/{id}', ['middleware' => 'permission:parecer.destroy', 'as' => 'destroy', 'uses' => 'ParecerController@destroy']);
    });

    Route::group(['prefix' => 'util', 'as' => 'util.'], function () {
        Route::post('search', ['as' => 'search', 'uses' => 'UtilController@search']);
        Route::post('select2', ['as' => 'select2', 'uses' => 'UtilController@queryByselect2']);
    });

    Route::group(['prefix' => 'default', 'as' => 'default.'], function () {
        Route::post('changeescola', ['as' => 'changeescola', 'uses' => 'DefaultController@changeEscola']);
    });

    Route::group(['prefix' => 'loadfields', 'as' => 'loadfields.'], function () {
        Route::post('getCalendarios', ['as' => 'getCalendarios', 'uses' => 'Relatorios\LoadFieldsReportsController@getCalendarios']);
        Route::post('getTurmaByCalendario', ['as' => 'getTurmaByCalendario', 'uses' => 'Relatorios\LoadFieldsReportsController@getTurmaByCalendario']);
        Route::post('getAlunosByTurma', ['as' => 'getAlunosByTurma', 'uses' => 'Relatorios\LoadFieldsReportsController@getAlunosByTurma']);
    });

    Route::group(['prefix' => 'relatorios', 'as' => 'relatorios.'], function () {

        Route::group(['prefix' => 'alunos', 'as' => 'alunos.'], function () {
            Route::get('fixa/{alunoId}', ['as' => 'fixa', 'uses' => 'Relatorios\Alunos\FixaDoAlunoController@index']);
        });

    });

});

# ROtas de autenticação
Route::group(['middleware' => 'web'], function () {
    Route::get('login', ['as' => 'index', 'uses' => 'Authentication\LoginController@login']);
    Route::post('attempt', ['as' => 'attempt', 'uses' => 'Authentication\LoginController@attempt']);

app/Http/Controllers/TurmaComplementarController.php
<?php

namespace SerEducacional\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use SerEducacional\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use SerEducacional\Repositories\TurmaComplementarRepository;
use SerEducacional\Services\TurmaComplementarService;
use SerEducacional\Validators\TurmaComplementarValidator;
use Yajra\Datatables\Datatables;


class TurmaComplementarController extends Controller
{
    /**
     * @var TurmaComplementarRepository
     */
    protected $repository;

    /**
     * @var TurmaComplementarValidator
     */
    protected $validator;

    /**
     * @var array
     */
    private $loadFields = [
        'QuantidadeAtividade',
        'Turno',       
        'Calendario',
        'TipoAtendimento',
        'Dependencia',
        'Escola'
    ];

    /**
     * @var TurmaComplementarService
     */
    private $service;

    /**
     * TurmaComplementarController constructor.
     * @param TurmaComplementarRepository $repository
     * @param TurmaComplementarValidator $validator
     * @param TurmaComplementarService $service
     */
    public function __construct(TurmaComplementarRepository $repository,
                                TurmaComplementarValidator $validator,
                                TurmaComplementarService $service)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        # Retorno para view
        return view('turmaComplementar.index');
    }

    /**
     * @return mixed
     */
    public function grid()
    {
        #Criando a consulta
        $rows = \DB::table('edu_turmas')
            ->join('edu_escola', 'edu_escola.id', '=', 'edu_turmas.escola_id')
            ->join('edu_tipos_atendimentos', 'edu_tipos_atendimentos.id', '=', 'edu_turmas.tipo_atendimento_id')
            ->join('edu_calendarios', 'edu_calendarios.id', '=', 'edu_turmas.calendario_id')
            ->join('edu_dependencias', 'edu_dependencias.id', '=', 'edu_turmas.dependencia_id')
            ->join('edu_turnos', 'edu_turnos.id', '=', 'edu_turmas.turno_id')
            ->where('edu_turmas.tipo_turma_id', 2)
            ->select([
                'edu_turmas.id',
                'edu_turmas.nome',
                'edu_turmas.codigo',
                'edu_escola.codigo as escola',
                'edu_turnos.nome as turno',
                'edu_turmas.vagas'
            ]);

        #Editando a grid
        return Datatables::of($rows)->addColumn('action', function ($row) {
            # Recuperando o usuário
            $user = Auth::user();

            # recuperando o curriculo
            $turma = $this->repository->find($row->id);

            # Html de uso
            $html  = '';

            # Verificando a permissão de editar
            if($user->can('turma.complementar.update')) {
                $html  = '<a style="margin-right: 5%;" title="Editar Turma Complementar"  href="edit/'.$row->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i></a>';
            }

            # Verificando se o currículo possui disciplinas
            if(count($turma->atividades) == 0 && count($turma->alunos) == 0 && $user->can('turma.complementar.destroy')) {
                # Html de delete
                $html .= '<a style="margin-right: 5%;" title="Remover Turma Complementar" href="destroy/'.$row->id.'"  class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-remove"></i></a>';
            }

            # Verificando a permissão de adicionar atividade
            if($user->can('turma.complementar.add.atividade')) {
                # Html de atividades
                $html .= '<a style="margin-right: 5%;" title="Atividades" id="btnModalAtividades" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-plus-sign"></i></a>';
            }

            # Verificando a permissão de adicionar alunos
            if($user->can('turma.complementar.add.aluno')) {
                # Html de alunos
                $html .= '<a title="Alunos" id="btnModalAlunos" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-plus-sign"></i></a>';
            }

            # Retorno
            return $html;
        })->make(true);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        #Carregando os dados para o cadastro
        $loadFields = $this->service->load($this->loadFields);

        #Retorno para view
        return view('turmaComplementar.create', compact('loadFields'));
    }

    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            #Recuperando os dados da requisição
            $data = $request->all();
        
            #Validando a requisição
            $this->validator->with($data)->passesOrFail(ValidatorInterface::RULE_CREATE);

            #Executando a ação
            $this->service->store($data);

            #Retorno para a view
            return redirect()->back()->with("message", "Cadastro realizado com sucesso!");
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($this->validator->errors())->withInput();
        } catch (\Throwable $e) { 
            return redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function edit($id)
    {
        try {
            #Recuperando a empresa
            $model = $this->repository->find($id);

            #Carregando os dados para o cadastro
            $loadFields = $this->service->load($this->loadFields);

            #retorno para view
            return view('turmaComplementar.edit', compact('model', 'loadFields'));
        } catch (\Throwable $e) {
            return redirect()->back()->with('message', $e->getMessage());
        }
    }


    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            #Recuperando os dados da requisição
            $data = $request->all();

            #tratando as rules
            $this->validator->replaceRules(ValidatorInterface::RULE_UPDATE, ":id", $id);

            #Validando a requisição
            $this->validator->with($data)->passesOrFail(ValidatorInterface::RULE_UPDATE);

            #Executando a ação
            $this->service->update($data, $id);

            #Retorno para a view
            return redirect()->back()->with("message", "Alteração realizada com sucesso!");
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        } catch (\Throwable $e) {
            return redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        try {
            #Executando a ação
            $this->service->destroy($id);

            #Retorno para a view
            return redirect()->back()->with("message", "Remoção realizada com sucesso!");
        } catch (\Throwable $e) {
            return redirect()->back()->with('message', $e->getMessage());
        }
    }
}

resources/views/turmaComplementar/create.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <section id="content">
            {{-- Mensagem de alerta quando os dados não atendem as regras de validação que foramd efinidas no servidor --}}
            <div class="ibox-content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif
            </div>
            {{-- Fim mensagem de alerta --}}
            {{--Formulario--}}
            {!! Form::open(['route'=>'turmaComplementar.store', 'id' => 'formTurmaComplementar', 'method' => "POST" ]) !!}
            @include('tamplatesForms.tamplateFormTurmaComplementar')
            {!! Form::close() !!}
            {{--Fim formulario--}}
        </section>
    </div>
@stop

resources/views/turmaComplementar/edit.blade.php
@extends('menu')

@section('content')
    <div class="container">
        <br>
        <div class="ibox-content">

            <section id="content">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                {!! Form::model($model, ['route'=> ['turmaComplementar.update', $model->id], 'id' => 'formTurmaComplementar', 'method' => "POST" ]) !!}
                @include('tamplatesForms.tamplateFormTurmaComplementar')
                {!! Form::close() !!}
            </section>
        </div>
    </div>
@stop

resources/views/turmaComplementar/index.blade.php
@extends('menu')

@section('content')
    <section id="content">
        <div class="container">
            <div class="block-header">
                <h2>Listar Turmas Complementares</h2>
            </div>

            <div class="card material-table">
                <div class="card-header">
                    @if(Session::has('message'))
                        <div class="alert alert-success">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <em> {!! session('message') !!}</em>
                        </div>
                    @endif

                    @if(Session::has('errors'))
                        <div class="alert alert-danger">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            @foreach($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                        </div>
                    @endif

                    @permission('turma.complementar.store')
                    <!-- Botão novo -->
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="text-right">
                                <a class="btn btn-primary btn-sm m-t-10", href="{{ route('turmaComplementar.create') }}">Nova Turma Complementar</a>
                            </div>
                        </div>
                    </div>
                    <!-- Botão novo -->
                    @endpermission
                </div>

                <div class="table-responsive">
                    <table id="turmaComplementar-grid" class="table table-hover">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Codigo</th>
                                <th>Escola</th>
                                <th>Turno</th>
                                <th>Açao</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Codigo</th>
                                <th>Escola</th>
                                <th>Turno</th>
                                <th style="width: 15%;">Açao</th>
                            </tr>
                            </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </section>

    @include('turmaComplementar.modal_atividades')
    @include('turmaComplementar.modal_alunos')
@stop

@section('javascript')
    @parent
    <script type="text/javascript" src="{{ asset('/dist/turmaComplementar/modal_atividades.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/dist/turmaComplementar/modal_alunos.js') }}"></script>
    <script type="text/javascript">
        var table = $('#turmaComplementar-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('turmaComplementar.grid') }}",
            columns: [
                {data: 'nome', name: 'edu_turmas.nome'},
                {data: 'codigo', name: 'edu_turmas.codigo'},
                {data: 'escola', name: 'edu_escola.codigo'},
                {data: 'turno', name: 'edu_turnos.nome'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

        // Global idTurmaComplementar
        var idTurmaComplementar;

        // Evento para abrir o modal de atividades
        $(document).on("click", "#btnModalAtividades", function () {
            // Recuperando o id da atividade
            idTurmaComplementar = table.row($(this).parents('tr')).data().id;

            // Recuperando o nome e o código
            var codigo = table.row($(this).parents('tr')).data().codigo;
            var nome   = table.row($(this).parents('tr')).data().nome;

            // prenchendo o titulo do modal de atividades
            $('#aNome').text(nome);
            $('#aCodigo').text(codigo);

            // Executando o modal
            runModalAtividades(idTurmaComplementar);
        });

        // Evento para abrir o modal de alunos
        $(document).on("click", "#btnModalAlunos", function () {
            // Recuperando o id da turma
            idTurmaComplementar = table.row($(this).parents('tr')).data().id;

            // Recuperando o nome e o código
            var codigo = table.row($(this).parents('tr')).data().codigo;
            var nome   = table.row($(this).parents('tr')).data().nome;
            var vagas  = table.row($(this).parents('tr')).data().vagas;

            // prenchendo o titulo do nome do aluno
            $('#alNome').text(nome);
            $('#alCodigo').text(codigo);
            $('#numMaxVagas').val(vagas);
            numAlunosMatriculados();

            // Executando o modal
            runModalAluno(idTurmaComplementar);
        });
    </script>
@stop

resources/views/turmaComplementar/modal_alunos.blade.php
<!-- Modal de cadastro das Disciplinas-->
<div id="modal-alunos" class="modal fade modal-profile" role="dialog" aria-labelledby="modalProfile" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Alunos</h4>
            </div>
            <div class="modal-body" style="alignment-baseline: central">
                <div class="row" style="margin-bottom: 5%; background-color: #D3D3D3; border-bottom: #696969 solid;">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-4">
                                    <span><strong>Código: </strong><p id="alCodigo"></p></span>
                                </div>

                                <div class="col-md-6">
                                    <span><strong>Nome: </strong><p id="alNome"></p></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <!-- Gerendiamento dos alunos -->
                    <div class="col-md-12">
                        <!-- campos de descrição das vagas da turma -->
                        <div class="row" style="margin-bottom: 2%;">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-3">
                                        <label for="numMaxVagas" class="label-control">Nº máximo de vagas</label>
                                        <input type="text" id="numMaxVagas" class="form-control" disabled>
                                    </div>

                                    <div class="col-md-3">
                                        <label for="numVagas">Alunos matriculados</label>
                                        <input type="text" id="numVagas" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Adicionar aluno -->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-10">
                                        <select id="select-alunos" class="form-control"></select>
                                    </div>

                                    <div class="col-md-2">
                                        <button class="btn btn-primary" id="addAluno" type="button">Adicionar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Fim Adicionar aluno -->

                        <!-- Table de alunos -->
                        <div class="table-responsive">
                            <table id="alunos-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th style="width: 10%;">Matrícula</th>
                                    <th>Nome</th>
                                    <th style="width: 5%;">Ação</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- Fim Table de alunos -->
                    </div>
                    <!-- Fim do Gerendiamento dos alunos -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FIM Modal de cadastro de alunos-->